title: Machine Learning
description: machine learning blog
author: Rishav Kumar
github: https://github.com/aptrishu
about: Machine Learning Engineer (wanna be)..
disqus_shortname: rishavjha-me
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/aptrishu"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/rishus23"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/aptrishu"

share:
  twitter_username: aptrishu
  fb_appid: 2015958435352782

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://aptrishu.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
