# Setup

# Permalinks
permalink:        pretty

# Setup
title:            Rishav
tagline:          'The personal website of Rishav'
description:      'The personal website of Rishav'
url:              rishu.codes

paginate:         1

github:
  repo:           github.com/aptrishu/aptrishu.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name:           'Rishav'
  url:            https://twitter.com/aptrishu

# Custom vars
version: 3.0.0
